services:
  cb-rates-service:
    image: cb-rates-service:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - CB-RATES-PROVIDER-URL-TEMPLATE=http://cb-rates-provider-service:8081/api/cb-rates?date={date}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
  cb-rates-provider-service:
    image: cb-rates-provider-service:1.0-SNAPSHOT
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
  kafka:
    image: apache/kafka:3.8.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_ADVERTISED_LISTENERS=LOCAL://localhost:9092,PLAINTEXT://kafka:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,LOCAL://:9092,PLAINTEXT://:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKER-CONNECT=kafka:9094
  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411