services:
  cb-rates-service:
    image: cb-rates-service:1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      CB-RATES-PROVIDER-URL-TEMPLATE: http://cb-rates-provider-service:8081/api/cb-rates?date={date}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      OTEL_EXPORTER_JAEGER_HOST: jaeger
  cb-rates-provider-service:
    image: cb-rates-provider-service:1.0-SNAPSHOT
    ports:
      - 8081:8081
    environment:
      OTEL_EXP ORTER_JAEGER_HOST: jaeger
  cb-rates-db-service:
    image: cb-rates-db-service:1.0-SNAPSHOT
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/cb_rates
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      OTEL_EXPORTER_JAEGER_HOST: jaeger
  kafka:
    image: apache/kafka:3.8.0
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,DOCKER://kafka:9094,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKER-CONNECT: kafka:9094
  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  db:
    image: postgres:16.0
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: cb_rates
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
