spring:
  application:
    name: cb-rates-provider-service

server:
  port: 8081

otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: jaeger-agent
  exporter:
    jaeger:
      host: localhost
      port: 6831
  resource:
    attributes:
      deployment.environment: local
      service:
        name: ${spring.application.name}
        namespace: tracing-demo